# Generated by Django 6.0.3 on 2026-04-23 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_weekly_loan_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='is_weekly',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_payment_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='mpesa_disburse_code',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='weekly_installment',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='weeks',
        ),
        migrations.AlterField(
            model_name='loan',
            name='arrears_count',
            field=models.IntegerField(default=0, help_text='Consecutive missed repayments — triggers 21% rate at 3'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='effective_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual rate applied (tier / arrears override)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_first_loan',
            field=models.BooleanField(default=True, help_text='True if first loan — determines KES 500 vs 300 fee'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Processing fee: KES 500 first loan, KES 300 repeat', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='initiation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy — use first_loan_fee / repeat_loan_fee', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='% per cycle', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('IDC', 'Individual Daily Collection (IDC)'), ('EDC', 'Every Day Collection (EDC)'), ('GDC', 'Group Daily Collection (GDC)'), ('IWC', 'Individual Weekly Collection (IWC)'), ('EWC', 'Every Week Collection (EWC)'), ('GWC', 'Group Weekly Collection (GWC)'), ('IMC', 'Individual Monthly Collection (IMC)'), ('IBC', 'Individual Bi-weekly Collection (IBC)'), ('IQC', 'Individual Quarterly Collection (IQC)'), ('FA', 'Salary Advance (FA)'), ('CC', 'Credit Check (CC)'), ('LOGBOOK', 'Logbook Loan'), ('CUSTOM', 'Custom')], max_length=10),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.5'), help_text='% per day', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='tenure_days',
            field=models.IntegerField(help_text='Loan duration in days'),
        ),
        migrations.AlterField(
            model_name='repaymentschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklyloanconfig',
            name='allowed_weeks',
            field=models.JSONField(default=list, help_text='Allowed loan durations e.g. [4, 6, 8]'),
        ),
        migrations.AlterField(
            model_name='weeklyloanconfig',
            name='first_loan_limit',
            field=models.DecimalField(decimal_places=2, default=5000, help_text='Max amount for a first-time borrower in this branch', max_digits=10),
        ),
        migrations.AlterField(
            model_name='weeklyloanconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weeklyloanconfig',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Weekly interest rate as % (5% = 20%/month)', max_digits=5),
        ),
    ]
