# Generated by Django 6.0.3 on 2026-04-23 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loan_is_weekly_remove_loan_last_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from verification team about document checks'),
        ),
        migrations.AddField(
            model_name='loan',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('VERIFIED', 'Verified by Team'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULT', 'Default'), ('WRITTEN_OFF', 'Written Off'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
    ]
