# Generated by Django 6.0.3 on 2026-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loan_disbursed_by_loan_verification_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='default_reason',
            field=models.CharField(blank=True, choices=[('SIMPLE_PAY_ERROR', 'Simple Pay system Error'), ('ADVERSE_BUSINESS_CYCLE', 'Adverse Business Cycle'), ('MPESA_NETWORK_DOWN', 'M-pesa Network Down'), ('BFC_NOT_UNDERSTAND', 'BFC-Did not Understand terms and Conditions'), ('BFC_MARKET_INFLUENCE', 'BFC-Influence from the market'), ('BFC_REFUSING_TO_PAY', 'BFC-Refusing to pay'), ('BUSINESS_POORLY', 'Business performing Poorly'), ('CLOSED_BUSINESS', 'Closed Business'), ('CUSTOMER_RELOCATED', 'Customer Relocated'), ('CUSTOMER_SICK', 'Customer Sick Or temporarily Incapacitated'), ('FAMILY_SICKNESS', 'Death and/or sickness in the family'), ('DELAYED_PAYMENTS', 'Delayed Payments by customers/Paid by cheque'), ('NATURAL_DISASTER', 'Environmental/Natural disaster'), ('FIRES', 'Fires'), ('MARKET_DISRUPTION', 'Market or Business Disruption'), ('POLITICAL_VIOLENCE', 'Political Violence'), ('THEFT', 'Theft-Proof of OB number'), ('TRAFFIC_DISRUPTION', 'Traffic disruption'), ('WRONG_STOCK', 'Wrong Stock Purchased')], help_text='Reason for loan default', max_length=30, null=True),
        ),
    ]
