# Generated by Django 6.0.3 on 2026-04-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_default_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='repeat_loan_fee',
            field=models.DecimalField(decimal_places=2, default=400, help_text='Processing fee for repeat borrowers (KES 400)', max_digits=10),
        ),
    ]
