# Generated by Django 6.0.3 on 2026-04-27 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_alter_loanproduct_repeat_loan_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='verification_team',
            field=models.ForeignKey(blank=True, help_text='Verification team member assigned to verify loans of this product', limit_choices_to={'role': 'VERIFICATION_TEAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
