# Generated by Django 6.0.3 on 2026-04-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_new_roles'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('GM', 'General Manager'), ('RM', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('HOP', 'Head of Products'), ('HOP_ASST', 'Assistant HOP'), ('OPERATIONS', 'Operations'), ('BDO', 'Business Development Officer'), ('BDM', 'Business Development Manager'), ('ASST_BDM', 'Assistant BDM'), ('IDC', 'IDC Credit Officer'), ('LOAN_OFFICER', 'Loan Officer'), ('CREDIT_OFFICER', 'Credit Officer'), ('FA_MANAGER', 'FA Manager'), ('ACCOUNTANT', 'Finance'), ('PAYMENT_OFFICER', 'Payment Officer'), ('DISBURSEMENT_OFFICER', 'Disbursement Officer'), ('COLLECTIONS_MGR', 'Collections Manager'), ('EDC_MANAGER', 'EDC Manager'), ('COLLECTIONS', 'Collections Officer'), ('EXTERNAL_DEBT_COLLECTOR', 'External Debt Collector'), ('FIELD_AGENT', 'Field Agent'), ('SURGE_TEAM', 'Surge Team Collections'), ('CC_MANAGER', 'CC Manager'), ('CALL_CENTRE', 'Call Centre'), ('MARKETING_MGR', 'Marketing Manager'), ('MARKETING_ASST', 'Marketing Assistant'), ('RO', 'Relationship Officer'), ('BA', 'Brand Ambassador'), ('FRONT_OFFICE', 'Front Office'), ('READ_ONLY', 'Viewer Only')], default='READ_ONLY', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
