# Generated by Django 6.0.3 on 2026-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_auditlog_id_alter_user_groups_alter_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('GM', 'General Manager'), ('RM', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('HOP', 'Head of Products'), ('HOP_ASST', 'Assistant HOP'), ('OPERATIONS', 'Operations'), ('BDO', 'Business Development Officer'), ('BDM', 'Business Development Manager'), ('ASST_BDM', 'Assistant BDM'), ('IDC', 'IDC Credit Officer'), ('LOAN_OFFICER', 'Loan Officer'), ('CREDIT_OFFICER', 'Credit Officer'), ('FA_MANAGER', 'FA Manager'), ('VERIFICATION_TEAM', 'Verification Team'), ('ACCOUNTANT', 'Finance'), ('PAYMENT_OFFICER', 'Payment Officer'), ('DISBURSEMENT_OFFICER', 'Disbursement Officer'), ('COLLECTIONS_MGR', 'Collections Manager'), ('EDC_MANAGER', 'EDC Manager'), ('COLLECTIONS', 'Collections Officer'), ('EXTERNAL_DEBT_COLLECTOR', 'External Debt Collector'), ('FIELD_AGENT', 'Field Agent'), ('SURGE_TEAM', 'Surge Team Collections'), ('CC_MANAGER', 'CC Manager'), ('CALL_CENTRE', 'Call Centre'), ('MARKETING_MGR', 'Marketing Manager'), ('MARKETING_ASST', 'Marketing Assistant'), ('RO', 'Relationship Officer'), ('BA', 'Brand Ambassador'), ('FRONT_OFFICE', 'Front Office'), ('READ_ONLY', 'Viewer Only')], default='READ_ONLY', max_length=30),
        ),
    ]
