# Generated by Django 6.0.3 on 2026-04-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('RM', 'Regional Manager'), ('BRANCH_MANAGER', 'Branch Manager'), ('OPERATIONS', 'Operations'), ('BDO', 'Business Development Officer'), ('IDC', 'IDC Credit Officer'), ('LOAN_OFFICER', 'Loan Officer'), ('FA_MANAGER', 'FA Manager'), ('VERIFICATION_TEAM', 'Verification Team'), ('FINANCE', 'Finance'), ('PAYMENT_OFFICER', 'Payment Officer'), ('DISBURSEMENT_OFFICER', 'Disbursement Officer'), ('COLLECTIONS_MGR', 'Collections Manager'), ('EDC_MANAGER', 'EDC Manager'), ('COLLECTIONS', 'Collections Officer'), ('EXTERNAL_DEBT_COLLECTOR', 'External Debt Collector'), ('FIELD_AGENT', 'Field Agent'), ('CC_MANAGER', 'CC Manager'), ('CALL_CENTRE', 'Call Centre'), ('FRONT_OFFICE', 'Front Office'), ('READ_ONLY', 'Viewer Only')], default='READ_ONLY', max_length=30),
        ),
    ]
