# Generated by Django 6.0.3 on 2026-04-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_add_submarket'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('BRANCH', 'Branch'), ('HQ', 'Headquarters')], default='BRANCH', help_text='Branch type: Regular Branch or Headquarters', max_length=10),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
