# Generated by Django 6.0.3 on 2026-05-02 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_customer_default_product_alter_customer_id_and_more'),
        ('loans', '0009_loanproduct_verification_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Customer name at time of interaction', max_length=255)),
                ('customer_phone', models.CharField(help_text='Customer phone number', max_length=20)),
                ('conversation_method', models.CharField(choices=[('PHONE', 'Phone Call'), ('SMS', 'SMS'), ('EMAIL', 'Email'), ('VISIT', 'Physical Visit'), ('WHATSAPP', 'WhatsApp'), ('OTHER', 'Other')], help_text='Method of communication', max_length=20)),
                ('conversation_purpose', models.CharField(choices=[('COLLECTION', 'Collections'), ('FOLLOW_UP', 'Follow Up'), ('VERIFICATION', 'Verification'), ('PAYMENT_REMINDER', 'Payment Reminder'), ('DEFAULT_NOTICE', 'Default Notice'), ('NEGOTIATION', 'Negotiation'), ('OTHER', 'Other')], help_text='Purpose of the conversation', max_length=30)),
                ('reason_for_default', models.CharField(blank=True, choices=[('FINANCIAL', 'Financial Difficulty'), ('EMPLOYMENT', 'Job Loss/Income Issue'), ('HEALTH', 'Health Emergency'), ('BUSINESS', 'Business Failure'), ('DISPUTE', 'Dispute over Loan'), ('FORGOTTEN', 'Forgot to Pay'), ('UNREACHABLE', 'Unreachable'), ('OTHER', 'Other')], help_text='Reason for default if applicable', max_length=30)),
                ('outcome', models.CharField(choices=[('PTP', 'Promise to Pay'), ('PAID', 'Payment Made'), ('RESTRUCTURE', 'Restructure Request'), ('DEFAULT', 'Default Confirmed'), ('REPOSSESSION', 'Repossession Initiated'), ('ESCALATED', 'Escalated'), ('NO_RESPONSE', 'No Response'), ('OTHER', 'Other')], help_text='Outcome of the interaction', max_length=30)),
                ('outcome_details', models.TextField(blank=True, help_text='Detailed narration of the outcome')),
                ('recording_file', models.FileField(blank=True, help_text='Audio recording of the conversation', null=True, upload_to='crm/recordings/%Y/%m/')),
                ('recording_transcript', models.TextField(blank=True, help_text='Transcript of the conversation')),
                ('next_interaction_date', models.DateField(blank=True, help_text='Date for next scheduled interaction', null=True)),
                ('next_step', models.CharField(blank=True, choices=[('VISIT', 'Physical Visit'), ('REPOSSESSION', 'Repossession'), ('ESCALATE', 'Escalate to Management'), ('CALL', 'Follow Up Call'), ('NOTICE', 'Send Legal Notice'), ('CLOSE', 'Close Case'), ('OTHER', 'Other')], help_text='Next planned action', max_length=30)),
                ('ptp_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Promised payment amount', max_digits=14, null=True)),
                ('ptp_date', models.DateField(blank=True, help_text='Promise to pay date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_interactions', to='customers.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_interactions', to='loans.loan')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Interaction',
                'verbose_name_plural': 'CRM Interactions',
                'db_table': 'crm_interactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
