# Generated by Django 6.0.3 on 2026-04-27 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_lead_extended_fields'),
        ('loans', '0009_loanproduct_verification_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_product',
            field=models.ForeignKey(blank=True, help_text='Default loan product for this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_customers', to='loans.loanproduct'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('PLATINUM', 'Platinum — 16% (≥ 5 clean loans, no arrears)'), ('GOLD', 'Gold — 18% (≥ 3 clean loans)'), ('SILVER', 'Silver — 20% (standard)')], default='SILVER', help_text='Determines interest rate: Platinum=16%, Gold=18%, Silver=20%', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tier_notes',
            field=models.TextField(blank=True, help_text='Reason for tier change'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tier_updated_at',
            field=models.DateTimeField(blank=True, help_text='When tier was last promoted or demoted', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='total_loans_paid',
            field=models.IntegerField(default=0, help_text='Count of fully repaid loans — used for tier calculation'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='bytes'),
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=12),
        ),
        migrations.AlterField(
            model_name='lead',
            name='submarket',
            field=models.CharField(blank=True, help_text='Sub-market/locality within the branch area', max_length=80),
        ),
    ]
