# Generated by Django 6.0.3 on 2026-04-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_mpesatransaction_id_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('PARTIAL', 'Partial Payment'), ('PENALTY', 'Penalty'), ('FIRST_TIME_FEE', 'First-time Applicant Fee'), ('REPEAT_FEE', 'Repeat Customer Processing Fee')], default='PARTIAL', max_length=20),
        ),
    ]
