# Generated by Django 6.0.3 on 2026-04-27 17:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_default_product_alter_customer_id_and_more'),
        ('groups', '0001_initial'),
        ('loans', '0009_loanproduct_verification_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouploan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grouploanshare',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grouploanshare',
            name='individual_loan',
            field=models.OneToOneField(blank=True, help_text='Individual loan record created from this share', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_share', to='loans.loan'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='guarantees',
            field=models.ManyToManyField(blank=True, help_text='Members this person guarantees', related_name='guaranteed_by', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='shares',
            field=models.IntegerField(default=1, help_text='Number of group shares held'),
        ),
        migrations.AlterField(
            model_name='loangroup',
            name='group_fund',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Group savings / guarantee fund', max_digits=14),
        ),
        migrations.AlterField(
            model_name='loangroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
